# Generated by Django 3.2.9 on 2021-12-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalTrainers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('qualifications', models.TextField(blank=True, max_length=254, null=True)),
                ('price_per_session', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_per_block_4', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('price_per_block_8', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('price_per_block_12', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
