# Generated by Django 3.2.9 on 2021-12-21 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='personaltrainers',
            options={'verbose_name_plural': 'Personal Trainers'},
        ),
    ]
