# Generated by Django 3.2.9 on 2021-12-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20211221_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='price',
            new_name='price_per_block',
        ),
        migrations.AddField(
            model_name='classes',
            name='price_per_class',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
